init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
    - stack.exe setup > nul
    - mkdir tixstrobes
    - stack.exe build --prefetch --dry-run --verbose & exit 0
    - ps: sleep 3600
