init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
    - appveyor-retry curl -ostack.zip -L https://www.stackage.org/stack/windows-x86_64
    - 7z x stack.zip stack.exe
    - git clone https://github.com/commercialhaskell/stack.git
    - cd stack
    - ..\stack.exe setup > nul
    - ..\stack.exe build --ghc-options "-eventlog -debug"
    - cd ..
build_script:
    - .\stack\.stack-work\install\03c0d273\bin\stack.exe build --prefetch --dry-run +RTS -l -Ds
cache:
    - C:\Users\appveyor\procexp.exe
